from typing import Optional
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage


class LeadState(TypedDict):
    # Identity
    lead_id: str
    """Unique identifier for the lead"""
    
    lead_name: str
    """Name of the lead"""
    
    phone: str
    """Phone number of the lead"""
    
    email: Optional[str]
    """Email address of the lead"""

    # Conversation
    messages: list[BaseMessage]
    """List of messages in the conversation"""

    last_agent_response: str
    """The last response generated by the agent"""
    
    last_agent_node: str
    """The last node agent responded from <questionnaire | faq>"""

    next_node: str
    """Next node to route to, set by intent_router to direct graph routing"""

    # Questionnaire tracking
    current_question_key: str
    """Current index of question"""

    answered_fields: dict
    """Question fields answered till now"""

    human_agent_requested: bool
    """Requested to connect with human"""

    greeting_step: int
    """0: not started, 1: identity confirmed, 2: timing confirmed, 3: interest confirmed → proceed to Q flow"""
    
    question_retry_counts: dict
    """Tracks retry count for each question field (field name → number of times asked)"""

    # Entity switch detection
    pending_switch: Optional[dict]
    """Entity switch detection: {'field': '<field_name>', 'new_value': '<new_value>'}"""

    # Multi-intent handling
    pending_sub_query: Optional[str]
    """Stores a pending sub-query from multi-intent handling"""
    
    pending_next_question_text: Optional[str]
    """Stores the next question text pending from multi-intent handling"""

    # Collected Lead Data
    course_interest: Optional[str]
    """ai_batch | fullstack_batch | campus_fullstack | campus_ai | dsa_batch"""

    student_status: Optional[str]
    """student | graduated | working_professional"""

    current_year: Optional[str]
    """Current study year if user is student"""
    
    passout_year: Optional[str]
    """Year user has passed out"""

    department: Optional[str]
    """The branch/department user will/has graduate"""
    
    training_mode: Optional[str]
    """online | offline"""

    class_type: Optional[str]
    """self_paced | live"""
    
    interested: Optional[bool]
    """If user is interested in joining the course"""
    
    join_date: Optional[str]
    """When user is interested in joining the course"""
    
    onboarding_requested: Optional[bool]
    """If user requests an onboarding form to join"""
    
    onboarding_email_sent: Optional[bool]
    """Have we sent an onboarding mail to user"""
    
    callback_requested: Optional[bool]
    """If user requested for a callback from human"""

    callback_time: Optional[str]            
    """When user requests for a callback"""

    # Meta
    disposition: str
    """Lead disposition: 'interested' | 'not_interested' | 'callback' | 'human_agent_callback' | 'end_call'"""
    
    call_ended: bool
    """Whether the call has ended"""
    
    looking_for_job: Optional[bool]
    """Job hunting status for graduated/working professional"""
    
    lead_score: int
    """Computed lead score from 0-100"""
    
    lead_classification: str
    """Lead classification: 'Hot Lead' | 'Warm Lead' | 'Cold Lead'"""
    
    callback_time_raw: Optional[str]
    """Raw natural language callback time phrase"""
    
    join_date_raw: Optional[str]
    """Raw natural language join date phrase"""

    # Call metrics
    conversation_id: Optional[str]
    """Unique identifier for the conversation session"""
    
    call_transcript: Optional[str]
    """Full transcript of the call"""
    
    call_summary: Optional[str]
    """Summary of the call"""
    
    call_start_time: Optional[str]
    """Timestamp when the call started"""
    
    call_end_time: Optional[str]
    """Timestamp when the call ended"""
    
    call_duration: Optional[int]
    """Duration of the call in seconds"""
